# Generated by Django 2.0.3 on 2018-05-08 18:58

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[(0, 'Gobernador'), (10, 'Secretario'), (11, 'Secretaria'), (21, 'Director'), (22, 'Directora'), (31, 'Coordinador'), (32, 'Coordinadora'), (99, 'Administrativo')], default=99, max_length=2)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=100, verbose_name='DNI')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo Profesional')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('icono', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='archivos/'), upload_to='')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('cuit', models.CharField(max_length=13, verbose_name='CUIT')),
                ('telefonos', models.CharField(max_length=100, verbose_name='Telefonos')),
                ('web', models.URLField(verbose_name='Web')),
                ('padre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Organismo')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='organismo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organismo'),
        ),
    ]
