# Generated by Django 2.0.3 on 2019-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190215_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Personal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono'),
        ),
    ]
