# Generated by Django 2.0.3 on 2018-05-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180508_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='cuit',
            field=models.CharField(max_length=13, null=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='padre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organismo'),
        ),
    ]
