# Generated by Django 2.1.3 on 2019-02-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190215_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='begda',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endda',
            field=models.DateField(default='9999-12-31'),
        ),
    ]
