# Generated by Django 2.0.3 on 2018-05-08 19:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180508_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='cuit',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='icono',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='archivos/'), upload_to=''),
        ),
    ]
