# Generated by Django 2.0.3 on 2018-05-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180508_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[(0, 'Gobernador'), (10, 'Secretario'), (11, 'Secretaria'), (12, 'Subsecretario'), (13, 'SubScretaria'), (21, 'Director'), (22, 'Directora'), (31, 'Coordinador'), (32, 'Coordinadora'), (99, 'Administrativo')], default=99, max_length=2),
        ),
    ]
