# Generated by Django 2.0.3 on 2018-05-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180508_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
