# Generated by Django 2.1.3 on 2019-02-15 13:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.IntegerField(choices=[(0, 'Gobernador'), (0, 'Vice Gobernador'), (10, 'Ministro'), (20, 'Secretario'), (21, 'Secretaria'), (22, 'Subsecretario'), (23, 'SubScretaria'), (31, 'Director'), (32, 'Directora'), (33, 'SubDirector'), (34, 'SubDirectora'), (41, 'Coordinador'), (42, 'Coordinadora'), (51, 'Consejal'), (52, 'Diputado'), (53, 'Senador'), (61, 'Juez'), (62, 'Fiscal'), (71, 'Intendente'), (72, 'Comisionado'), (81, 'Escribano'), (82, 'Presidente'), (83, 'Vice Presidente'), (91, 'Administrativo'), (92, 'Jefe'), (93, 'Obispo'), (94, 'Sacerdote'), (95, 'Consul'), (96, 'Asesor')], default=99),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='descripcion',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web'),
        ),
    ]
