# Generated by Django 2.0.3 on 2019-02-15 14:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190215_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='archivos/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.IntegerField(choices=[(0, 'Gobernador'), (0, 'Vice Gobernador'), (10, 'Ministro'), (20, 'Secretario'), (21, 'Secretaria'), (22, 'Subsecretario'), (23, 'SubScretaria'), (31, 'Director'), (32, 'Directora'), (33, 'SubDirector'), (34, 'SubDirectora'), (41, 'Coordinador'), (42, 'Coordinadora'), (51, 'Consejal'), (52, 'Diputado'), (53, 'Senador'), (61, 'Juez'), (62, 'Fiscal'), (63, 'Vocal'), (71, 'Intendente'), (72, 'Comisionado'), (81, 'Escribano'), (82, 'Presidente'), (83, 'Vice Presidente'), (91, 'Administrativo'), (92, 'Jefe'), (93, 'Obispo'), (94, 'Sacerdote'), (95, 'Consul'), (96, 'Asesor')], default=99),
        ),
    ]
