# Generated by Django 2.1.3 on 2019-02-26 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190226_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='begda',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Designacion'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endda',
            field=models.DateField(default='9999-12-31', verbose_name='Cese de Funciones'),
        ),
    ]
