# Generated by Django 2.1.3 on 2019-04-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190228_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='decreto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
