# Generated by Django 2.1.3 on 2019-04-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_funcionario_decreto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='begda',
            field=models.DateField(auto_now=True, verbose_name='Designacion'),
        ),
    ]
