# Generated by Django 2.1.3 on 2019-04-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190403_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='begda',
            field=models.DateField(verbose_name='Designacion'),
        ),
    ]
