# Generated by Django 2.1.3 on 2019-04-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190403_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='begda',
        ),
    ]
