# Generated by Django 2.1.3 on 2019-04-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_funcionario_begda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='endda',
        ),
    ]
