# Generated by Django 2.1.3 on 2019-04-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_funcionario_endda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='decreto',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='titulo',
        ),
    ]
