# Generated by Django 2.1.3 on 2019-04-03 20:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='apellidos',
            field=models.CharField(default='testing', max_length=100, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='dni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='archivos/'), upload_to=''),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='titulo',
            field=models.CharField(default='testing', max_length=20, verbose_name='Titulo Profesional'),
            preserve_default=False,
        ),
    ]
