# Generated by Django 2.1.3 on 2019-04-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190403_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='decreto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Personal'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono'),
        ),
    ]
