# Generated by Django 2.1.3 on 2019-04-03 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190403_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='begda',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Designacion'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endda',
            field=models.DateField(default=datetime.date(9999, 12, 31), verbose_name='Cese de Funciones'),
        ),
    ]
