# Generated by Django 2.1.3 on 2019-04-03 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_funcionario_begda'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='begda',
            field=models.DateField(default=datetime.date(2019, 1, 1), verbose_name='Designacion'),
        ),
    ]
