# Generated by Django 2.1.3 on 2019-04-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='core.Organismo'),
        ),
    ]
