# Generated by Django 2.1.3 on 2019-04-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190403_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='subcargo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SubCargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcion_unica',
            field=models.BooleanField(default=False),
        ),
    ]
