# Generated by Django 2.1.3 on 2019-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190405_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismo',
            name='jerarquia',
            field=models.IntegerField(choices=[(0, 'Sin Jerarquia'), (10, 'Poder'), (20, 'Gobernacion'), (30, 'Ministerio'), (31, 'Secretaria'), (32, 'SubSecretaria'), (33, 'Direccion'), (34, 'Coordinacion'), (40, 'Senado'), (50, 'Judicial'), (60, 'Municipio'), (61, 'Intendencia'), (62, 'Consejo'), (70, 'Escleciastico'), (80, 'Privados')], default=0),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.IntegerField(choices=[(0, 'Sin Cargo'), (1, 'Gobernador'), (2, 'Vice Gobernador'), (10, 'Ministro'), (20, 'Secretario'), (21, 'Secretaria'), (22, 'Subsecretario'), (23, 'SubScretaria'), (31, 'Director'), (32, 'Directora'), (33, 'SubDirector'), (34, 'SubDirectora'), (41, 'Coordinador'), (42, 'Coordinadora'), (51, 'Consejal'), (52, 'Diputado'), (53, 'Senador'), (54, 'Diputada'), (55, 'Senadora'), (61, 'Juez'), (62, 'Fiscal'), (63, 'Vocal'), (64, 'Procurador'), (65, 'Procuradora'), (66, 'Defensor'), (71, 'Intendente'), (72, 'Comisionado'), (81, 'Escribano'), (82, 'Presidente'), (83, 'Vice Presidente'), (91, 'Administrativo'), (92, 'Jefe'), (93, 'Obispo'), (94, 'Sacerdote'), (95, 'Parroco'), (97, 'Consul'), (99, 'Asesor')], default=0),
        ),
    ]
