# Generated by Django 2.2 on 2019-04-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190423_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='jerarquia',
            field=models.IntegerField(choices=[(0, 'Sin Jerarquia'), (10, 'Poder Gubernamental'), (20, 'Gobernacion'), (30, 'Ministerio'), (31, 'Secretaria'), (32, 'SubSecretaria'), (33, 'Direccion'), (34, 'Coordinacion'), (40, 'Legislativo'), (50, 'Judicial'), (60, 'Municipio'), (61, 'Intendencia'), (62, 'Consejo'), (70, 'Escleciastico'), (80, 'Privados')], default=0),
        ),
    ]
