# Generated by Django 2.1.3 on 2019-04-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190423_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='telefonos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefonos'),
        ),
    ]
