# Generated by Django 2.1.3 on 2019-04-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190423_1752'),
        ('core', '0027_auto_20190423_1618'),
    ]

    operations = [
    ]
